apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
  spec: 
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    selector:
      matchLabels:
        app: todo-app
    template:
      metadata:
        labels:
          app: todo-app
      spec:
        containers:
        - name: app
          image: docker.io/monkthegreat/nodejs-todo:460aec2243aafa02f70c03e69c284ff3e31101d2
          ports:
          - containerPort: 5000
          env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: todo-config
                key: NODE_ENV
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: MONGO_URI
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initDelaySeconds: 5
            periodSeconds: 5
