# Указывание версии API и типа ресурса (Secret — защищенное хранилище паролей и токенов)
apiVersion: v1
kind: Secret

# Метаданные: имя секрета и пространство имен, где он будет использоваться
metadata:
  name: todo-secret
  namespace: todo-app

# Тип секрета: Opaque означает стандартный секрет с произвольными текстовыми данными
type: Opaque

# Зашифрованные данные: значения обязательно должны быть закодированы в формат Base64
data:
  # Ключ MONGO_URI хранит строку подключения к базе данных MongoDB с логином и паролем
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnNlY3JldEBtb25nby1zZXJ2aWNlOjI3MDE3L3RvZG8/YXV0aFNvdXJjZT1hZG1pbg==