apiVersion: v1
kind: secrets
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnNlY3JldEBtb25nby1zZXJ2aWNlOjI3MDE3L3RvZG8/YXV0aFNvdXJjZT1hZG1pbg==